module.exports= {Array:168,
  'Dynamic Programming':139,
  Math:129,
  String:123,
  Tree:114,
  'Hash Table':104,
  'Depth - first Search':99,
  'Binary Search':67,
  'Two Pointers':56,
  Greedy:52,
  'Breadth - first Search':49,
  Stack:49,
  Backtracking:41,
  Design:38,
  'Linked List':35,
  Heap:33,
  'Bit Manipulation':32,
  Sort:29,
  Graph:26,
  'Union Find':22,
  'Divide and Conquer':18,
  Trie:16,
  Recursion:14,
  'Sliding Window':14,
  'Ordered Map':10,
  'Segment Tree':10,
  Queue:9,
  Minimax:8,
  'Binary indexed Tree':6,
  Random:6,
  'Topological Sort':5,
  Brainteaser:4,
  Geometry:3,
  'Line Sweep':3,
  'Rejection Sampling':2,
  'Reservoir Sampling':2,
  'Binary Search Tree':1,
  Memoization:1
  }